baseURL: 'https://sysreboot.org/'
languageCode: 'en-us'
title: 'System Reboot Engineer'
theme: 'PaperMod'
pagination:
  pagerSize: 5

menu:
  main:
    - identifier: Home
      name: Home
      url: /post/
      weight: 10
    - identifier: About
      name: About
      url: /about/
      weight: 20
    - identifier: Book
      name: Book
      url: /book/book/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 40
    # - identifier: Lyrics
    #   name: Lyrics
    #   url: /lyric/
    #   weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

params:
  defaultTheme: dark
  ShowReadingTime: true
  ShowWordCount: true
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Hi there! I'm Long, a DevOps/Cloud Engineer. I created this website to share knowledge and experiences from my journey in the IT industry. Whether you're a professional or just curious about DevOps and cloud computing, I hope you find something useful here."
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/pikalong/"
    - name: "github"
      url: "https://github.com/lnvn"

